# Generated by Django 5.0 on 2024-01-14 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="travel_profile",
            name="location",
        ),
        migrations.AddField(
            model_name="travel_profile",
            name="city",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="travel_profiles",
                to="travel.city",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="travel_profile",
            name="name",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
