# Generated by Django 5.0 on 2024-01-17 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel", "0002_remove_travel_profile_location_travel_profile_city_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vacation_type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="travel_profile",
            name="adults",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="travel_profile",
            name="autocomplete_city",
            field=models.ForeignKey(
                blank=True,
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="travel_profiles",
                to="travel.city_autocomplete",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="travel_profile",
            name="children",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="travel_profile",
            name="preffered_airports",
            field=models.ManyToManyField(
                related_name="travel_profiles", to="travel.airport"
            ),
        ),
        migrations.AlterField(
            model_name="travel_profile",
            name="city",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="travel_profiles",
                to="travel.city",
            ),
        ),
        migrations.AddField(
            model_name="travel_profile",
            name="vacation_type",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="travel.vacation_type",
            ),
        ),
    ]
