# Generated by Django 5.0 on 2024-01-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel", "0003_vacation_type_travel_profile_adults_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="travel_profile",
            name="vacation_type",
        ),
        migrations.AddField(
            model_name="travel_profile",
            name="vacation_type",
            field=models.ManyToManyField(default=0, to="travel.vacation_type"),
        ),
    ]
