# Generated by Django 5.0 on 2024-01-21 21:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("travel", "0004_remove_travel_profile_vacation_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="travel_profile",
            old_name="vacation_type",
            new_name="vacation_types",
        ),
    ]
