# Generated by Django 5.0 on 2024-01-30 20:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("travel", "0007_rename_airport_suitability_suitable_airport_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Profile_destinations",
            new_name="Profile_destination",
        ),
    ]
