# Generated by Django 5.0 on 2024-02-04 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel", "0008_rename_profile_destinations_profile_destination"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="subsequent_flight_id",
            field=models.IntegerField(default=None),
        ),
        migrations.CreateModel(
            name="Travel_offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("duration_days", models.IntegerField()),
                ("flight_price", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "departure_flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_offers_departing",
                        to="travel.flight",
                    ),
                ),
                (
                    "destination_airport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_travel_offers",
                        to="travel.airport",
                    ),
                ),
                (
                    "return_flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_offers_returning",
                        to="travel.flight",
                    ),
                ),
                (
                    "travel_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_offers",
                        to="travel.travel_profile",
                    ),
                ),
            ],
        ),
    ]
