# Generated by Django 5.0 on 2024-02-04 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel", "0011_alter_flight_identifier"),
    ]

    operations = [
        migrations.CreateModel(
            name="Flight_route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=100, unique=True)),
                ("departure_date", models.DateField()),
                ("arrival_date", models.DateField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arrival_routes",
                        to="travel.airport",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departure_routes",
                        to="travel.airport",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="travel_offer",
            name="departure_flight",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="travel_offers_departing",
                to="travel.flight_route",
            ),
        ),
        migrations.AlterField(
            model_name="travel_offer",
            name="return_flight",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="travel_offers_returning",
                to="travel.flight_route",
            ),
        ),
        migrations.CreateModel(
            name="Single_flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=100, unique=True)),
                ("departure_date", models.DateField()),
                ("arrival_date", models.DateField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "carrier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flights",
                        to="travel.airline",
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arrivals",
                        to="travel.airport",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departures",
                        to="travel.airport",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="flight_route",
            name="flights",
            field=models.ManyToManyField(
                related_name="routes", to="travel.single_flight"
            ),
        ),
        migrations.DeleteModel(
            name="Flight",
        ),
    ]
