# Generated by Django 5.0 on 2024-02-12 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel", "0013_alter_flight_route_identifier_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile_destination",
            name="airport",
        ),
        migrations.AddField(
            model_name="profile_destination",
            name="destination_airport",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_destination_airports",
                to="travel.airport",
            ),
        ),
        migrations.AddField(
            model_name="profile_destination",
            name="origin_airport",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_origin_airports",
                to="travel.airport",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile_destination",
            name="travel_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_destinations",
                to="travel.travel_profile",
            ),
        ),
        migrations.CreateModel(
            name="Possible_destination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "destination",
                    models.ManyToManyField(
                        default=0, related_name="destination_for", to="travel.airport"
                    ),
                ),
                (
                    "origin",
                    models.ManyToManyField(
                        related_name="origin_for", to="travel.airport"
                    ),
                ),
            ],
        ),
    ]
