# Generated by Django 5.0 on 2024-02-25 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel", "0015_alter_single_flight_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accomodation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name="travel_offer",
            name="departure_flight",
        ),
        migrations.RemoveField(
            model_name="travel_offer",
            name="duration_days",
        ),
        migrations.RemoveField(
            model_name="travel_offer",
            name="flight_price",
        ),
        migrations.RemoveField(
            model_name="travel_offer",
            name="return_flight",
        ),
        migrations.RemoveField(
            model_name="travel_profile",
            name="vacation_types",
        ),
        migrations.AddField(
            model_name="travel_offer",
            name="departure_routes",
            field=models.ManyToManyField(
                related_name="travel_offers_departing", to="travel.flight_route"
            ),
        ),
        migrations.AddField(
            model_name="travel_offer",
            name="itinerary",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="travel_offer",
            name="origin_airport",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="origin_in_travel_offers",
                to="travel.airport",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="travel_offer",
            name="return_routes",
            field=models.ManyToManyField(
                related_name="travel_offers_returning", to="travel.flight_route"
            ),
        ),
        migrations.AddField(
            model_name="travel_profile",
            name="vacation_type",
            field=models.ManyToManyField(default=1, to="travel.vacation_type"),
        ),
        migrations.AlterField(
            model_name="travel_offer",
            name="destination_airport",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="destination_in_travel_offers",
                to="travel.airport",
            ),
        ),
        migrations.AddField(
            model_name="travel_offer",
            name="accomodation",
            field=models.ManyToManyField(
                related_name="travel_offers", to="travel.accomodation"
            ),
        ),
    ]
