# Generated by Django 5.0 on 2024-02-25 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel", "0016_accomodation_remove_travel_offer_departure_flight_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="travel_profile",
            name="vacation_type",
        ),
        migrations.AddField(
            model_name="travel_profile",
            name="vacation_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="travel.vacation_type",
            ),
        ),
    ]
