# Generated by Django 5.0 on 2024-02-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel", "0017_remove_travel_profile_vacation_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityPreferebce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="DiningPreferebce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=300)),
            ],
        ),
    ]
