# Generated by Django 5.0 on 2024-02-28 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel", "0018_activitypreferebce_diningpreferebce"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DiningPreferebce",
            new_name="DiningPreference",
        ),
        migrations.AddField(
            model_name="travel_profile",
            name="activity_preference",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="travel.activitypreferebce",
            ),
        ),
        migrations.AddField(
            model_name="travel_profile",
            name="dining_preference",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="travel.diningpreference",
            ),
        ),
    ]
