# Generated by Django 5.0 on 2024-03-09 19:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("travel", "0019_rename_diningpreferebce_diningpreference_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="travel_offer",
            name="itinerary",
        ),
    ]
