# Generated by Django 5.0 on 2024-03-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel", "0020_remove_travel_offer_itinerary"),
    ]

    operations = [
        migrations.AddField(
            model_name="travel_offer",
            name="itinerary",
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
