# Generated by Django 5.0 on 2024-03-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel", "0021_travel_offer_itinerary"),
    ]

    operations = [
        migrations.CreateModel(
            name="Itinerary_image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("url", models.CharField(max_length=500)),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name="travel_offer",
            name="image",
            field=models.ManyToManyField(
                related_name="in_offers", to="travel.itinerary_image"
            ),
        ),
    ]
