# Generated by Django 5.0 on 2024-03-25 20:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("travel", "0022_itinerary_image_travel_offer_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ActivityPreferebce",
            new_name="ActivityPreference",
        ),
    ]
