# Generated by Django 5.0 on 2024-04-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel", "0024_alter_travel_offer_travel_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="travel_offer",
            name="travel_profile",
            field=models.ForeignKey(
                on_delete=models.SET(1),
                related_name="travel_offers",
                to="travel.travel_profile",
            ),
        ),
    ]
