# Generated by Django 4.2.7 on 2023-11-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0004_alter_follow_follower_alter_like_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="text",
            field=models.CharField(max_length=400),
        ),
    ]
